version: '3.8'
services:
  badminton-service:
    image: node:14.15.1
    ports:
      - "8080:8080"
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env
    command: ['/bin/sh', '-c', 'yarn && yarn dev']
networks:
  default:
    external:
      name: badmintonnetwork
